### ISSUE TITLE
Sensor Status is Unknown

### ISSUE THREAD

**Issue by ASMediaDev** [FaserF/ha-deutschebahn#56]
### The problem

Since mid of october, the integration is not working for me anymore.
I get this error in the logs:

```
This error originated from a custom integration.

Logger: custom_components.deutschebahn.sensor
Source: custom_components/deutschebahn/sensor.py:154
integration: Deutsche Bahn (documentation, issues)
First occurred: October 23, 2024 at 10:21:54 (6556 occurrences)
Last logged: 09:09:58

Requested 2 connections, but only 1 are available.
```

This morning I also noticed this error:
```

This error originated from a custom integration.

Logger: custom_components.deutschebahn.sensor
Source: custom_components/deutschebahn/sensor.py:139
integration: Deutsche Bahn (documentation, issues)
First occurred: 08:49:58 (2 occurrences)
Last logged: 08:49:58

Cannot retrieve data for direction: 'Roth' 'Schwabach' - Most likely it is a temporary API issue from DB and will stop working after a HA restart/some time.
Cannot retrieve data for direction: 'Roth' 'Nuremberg' - Most likely it is a temporary API issue from DB and will stop working after a HA restart/some time.
Traceback (most recent call last):
  File "/config/custom_components/deutschebahn/sensor.py", line 143, in async_update
    self.connections = await hass.async_add_executor_job(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deutschebahn/sensor.py", line 139, in async_update
    with async_timeout.timeout(30):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 128, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError
```

### What version of Home Assistant Core has the issue?

2024.10.3

### What version of DeutscheBahn Integration has the issue?

3.0.3

### What type of installation are you running?

Home Assistant OS

**Comment by tolu-001** [comment]
Same problem here - anyone working on it?
